# Generated by Django 4.1.2 on 2022-10-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.CharField(default='DD-MM-AAAA', max_length=12, blank=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_reserva',
            field=models.CharField(default='HH:MM', max_length=5, blank=True),
        ),
    ]
