# Generated by Django 4.1.2 on 2022-10-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0002_alter_reserva_fecha_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.CharField(blank=True, default='DD-MM-AAAA', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_reserva',
            field=models.CharField(blank=True, default='HH:MM', max_length=5, null=True),
        ),
    ]
