# Generated by Django 4.1.2 on 2022-10-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0003_alter_reserva_fecha_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='numero_plato',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
