# Generated by Django 4.1.2 on 2022-10-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0004_alter_reserva_numero_plato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='pedido',
            field=models.CharField(blank=True, choices=[('D', 'Delivery'), ('R', 'Restaurante')], default='R', max_length=2, null=True),
        ),
    ]
