# Generated by Django 4.1.2 on 2022-10-10 02:08

from django.db import migrations, models
import restApp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0007_alter_reserva_cliente_id_alter_reserva_fecha_reserva_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.IntegerField(validators=[restApp.validators.validar_precio]),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero_plato',
            field=models.IntegerField(blank=True, validators=[restApp.validators.validar_platos]),
        ),
    ]
