# Generated by Django 4.1.2 on 2022-10-10 02:23

from django.db import migrations, models
import restApp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0008_rename_cliente_id_reserva_cliente_alter_plato_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='numero_plato',
            field=models.IntegerField(blank=True, null=True, validators=[restApp.validators.validar_platos]),
        ),
    ]
